version: '3'

services:

  app:
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://uk6uvzwqnfo6139d:VnImjK9miylDRqh3AuLi@bm0bdzlz9oak5nzjpvlv-mysql.services.clever-cloud.com:3306/bm0bdzlz9oak5nzjpvlv
      SPRING_DATASOURCE_USERNAME: uk6uvzwqnfo6139d
      SPRING_DATASOURCE_PASSWORD: VnImjK9miylDRqh3AuLi
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver